### ISSUE TITLE
Getting NPE in Packet Send

### ISSUE THREAD

**Issue by castlec** [bundabrg/GeyserReversion#12]
``
java.lang.NullPointerException: null
	at au.com.grieve.reversion.shaded.nukkitx.protocol.util.Int2ObjectBiMap.get(Int2ObjectBiMap.java:52) ~[?:?]
	at au.com.grieve.reversion.shaded.nukkitx.protocol.bedrock.BedrockPacketCodec.getId(BedrockPacketCodec.java:87) ~[?:?]
	at au.com.grieve.reversion.shaded.nukkitx.protocol.bedrock.BedrockSession.checkPacket(BedrockSession.java:112) ~[?:?]
	at au.com.grieve.reversion.shaded.nukkitx.protocol.bedrock.BedrockSession.sendPacket(BedrockSession.java:90) ~[?:?]
	at au.com.grieve.geyser.reversion.server.GeyserServerSession.sendPacket(GeyserServerSession.java:57) ~[?:?]
``

Perhaps a version change on the client? 

[15:22:01 INFO] Loading Geyser version 1.2.0-SNAPSHOT (git-73cd77bb50453281baf0e365cab8c26c3e8029c5-73cd77b)
[15:22:01 INFO] 
[15:22:01 INFO] ******************************************
[15:22:01 INFO] {GeyserReversion} Loading GeyserReversion v1.0.13

**Comment by bundabrg** [comment]
Thanks for the report. This should be solved now in v1.0.14
