### ISSUE TITLE
Bossbar Error

### ISSUE THREAD

**Issue by Hellohi3654** [bundabrg/GeyserReversion#17]
A error appears when using geyser reversion

**Comment by Hellohi3654** [comment]
and bossbar's aren't removed

**Comment by bundabrg** [comment]
Stack trace of the error:
```
[04:10:45 ERROR] Could not translate packet ServerBossBarPacket
com.nukkitx.protocol.bedrock.exception.PacketSerializeException: Error whilst serializing BossEventPacket(bossUniqueEntityId=118, action=REMOVE, playerUniqueEntityId=0, title=null, healthPercentage=0.0, darkenSky=0, color=0, overlay=0)
        at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryEncode(BedrockPacketCodec.java:82) ~[Geyser-v1.16-b41.jar:?]
        at au.com.grieve.geyser.reversion.server.GeyserServerSession.sendPacket(GeyserServerSession.java:59) ~[?:?]
        at org.geysermc.connector.network.session.UpstreamSession.sendPacket(UpstreamSession.java:45) ~[Geyser-v1.16-b41.jar:?]
        at org.geysermc.connector.network.session.GeyserSession.lambda$sendUpstreamPacket$4(GeyserSession.java:852) ~[Geyser-v1.16-b41.jar:?]
        at org.geysermc.connector.event.EventResult.onNotCancelled(EventResult.java:59) ~[Geyser-v1.16-b41.jar:?]
        at org.geysermc.connector.network.session.GeyserSession.sendUpstreamPacket(GeyserSession.java:850) ~[Geyser-v1.16-b41.jar:?]
        at org.geysermc.connector.network.session.cache.BossBar.removeBossBar(BossBar.java:95) ~[Geyser-v1.16-b41.jar:?]
        at org.geysermc.connector.network.session.cache.EntityCache.removeBossBar(EntityCache.java:135) ~[Geyser-v1.16-b41.jar:?]
        at org.geysermc.connector.network.translators.java.JavaBossBarTranslator.translate(JavaBossBarTranslator.java:53) ~[Geyser-v1.16-b41.jar:?]
        at org.geysermc.connector.network.translators.java.JavaBossBarTranslator.translate(JavaBossBarTranslator.java:35) ~[Geyser-v1.16-b41.jar:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:100) [Geyser-v1.16-b41.jar:?]
        at org.geysermc.connector.network.session.GeyserSession.handleDownstreamPacket(GeyserSession.java:628) [Geyser-v1.16-b41.jar:?]
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:577) [Geyser-v1.16-b41.jar:?]
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) [Geyser-v1.16-b41.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) [Geyser-v1.16-b41.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) [Geyser-v1.16-b41.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.RuntimeException: BossEvent transactionType was unknown!
        at com.nukkitx.protocol.bedrock.v291.serializer.BossEventSerializer_v291.serialize(BossEventSerializer_v291.java:43) ~[Geyser-v1.16-b41.jar:?]
        at com.nukkitx.protocol.bedrock.v291.serializer.BossEventSerializer_v291.serialize(BossEventSerializer_v291.java:11) ~[Geyser-v1.16-b41.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryEncode(BedrockPacketCodec.java:80) ~[Geyser-v1.16-b41.jar:?]
        ... 16 more
> @szcom.nukkitx.protocol.bedrock.exception.PacketSerializeException: Error whilst serializing BossEventPacket(bossUniqueEntityId=118, action=REMOVE, playerUniqueEntityId=0, title=null, healthPercentage=0.0, darkenSky=0, color=0, overlay=0)
        at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryEncode(BedrockPacketCodec.java:82)
        at au.com.grieve.geyser.reversion.server.GeyserServerSession.sendPacket(GeyserServerSession.java:59)
        at org.geysermc.connector.network.session.UpstreamSession.sendPacket(UpstreamSession.java:45)
        at org.geysermc.connector.network.session.GeyserSession.lambda$sendUpstreamPacket$4(GeyserSession.java:852)
        at org.geysermc.connector.event.EventResult.onNotCancelled(EventResult.java:59)
        at org.geysermc.connector.network.session.GeyserSession.sendUpstreamPacket(GeyserSession.java:850)
        at org.geysermc.connector.network.session.cache.BossBar.removeBossBar(BossBar.java:95)
        at org.geysermc.connector.network.session.cache.EntityCache.removeBossBar(EntityCache.java:135)
        at org.geysermc.connector.network.translators.java.JavaBossBarTranslator.translate(JavaBossBarTranslator.java:53)
        at org.geysermc.connector.network.translators.java.JavaBossBarTranslator.translate(JavaBossBarTranslator.java:35)
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:100)
        at org.geysermc.connector.network.session.GeyserSession.handleDownstreamPacket(GeyserSession.java:628)
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:577)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: BossEvent transactionType was unknown!
        at com.nukkitx.protocol.bedrock.v291.serializer.BossEventSerializer_v291.serialize(BossEventSerializer_v291.java:43)
        at com.nukkitx.protocol.bedrock.v291.serializer.BossEventSerializer_v291.serialize(BossEventSerializer_v291.java:11)
        at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryEncode(BedrockPacketCodec.java:80)
        ... 16 more
```

**Comment by bundabrg** [comment]
Upstream issue. Closed by https://github.com/GeyserMC/Geyser/pull/1592
