### ISSUE TITLE
Issue connecting from a Nintendo Switch

### ISSUE THREAD

**Issue by bundabrg** [bundabrg/GeyserReversion#28]
```
[03:58:19 ERROR] An exception occurred in RakNet (Server)
java.lang.NullPointerException: null
        at org.geysermc.connector.skin.SkinManager$GameProfileData.from(SkinManager.java:278) ~[Geyser-v1.16-b46.jar:?]
        at org.geysermc.connector.skin.SkinManager.buildCachedEntry(SkinManager.java:53) ~[Geyser-v1.16-b46.jar:?]
        at org.geysermc.connector.network.session.GeyserSession.connect(GeyserSession.java:373) ~[Geyser-v1.16-b46.jar:?]
        at org.geysermc.connector.network.UpstreamPacketHandler.handle(UpstreamPacketHandler.java:125) ~[Geyser-v1.16-b46.jar:?]
        at com.nukkitx.protocol.bedrock.packet.ResourcePackClientResponsePacket.handle(ResourcePackClientResponsePacket.java:20) ~[Geyser-v1.16-b46.jar:?]
        at au.com.grieve.geyser.reversion.editions.bedrock.handlers.BedrockEditionUpstreamPacketHandler.handlePacket(BedrockEditionUpstreamPacketHandler.java:59) ~[?:?]
        at au.com.grieve.geyser.reversion.editions.bedrock.handlers.BedrockEditionUpstreamPacketHandler.handle(BedrockEditionUpstreamPacketHandler.java:324) ~[?:?]
        at au.com.grieve.reversion.shaded.nukkitx.protocol.bedrock.packet.ResourcePackClientResponsePacket.handle(ResourcePackClientResponsePacket.java:20) ~[?:?]
        at au.com.grieve.reversion.editions.bedrock.BedrockReversionSession.toServer(BedrockReversionSession.java:116) ~[?:?]
        at au.com.grieve.reversion.editions.bedrock.BedrockReversionSession$ReversionBatchHandler.handle(BedrockReversionSession.java:212) ~[?:?]
        at au.com.grieve.reversion.shaded.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:288) ~[?:?]
        at au.com.grieve.reversion.shaded.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32) ~[?:?]
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:300) ~[Geyser-v1.16-b46.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:427) ~[Geyser-v1.16-b46.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:405) ~[Geyser-v1.16-b46.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:398) ~[Geyser-v1.16-b46.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:272) ~[Geyser-v1.16-b46.jar:?]
        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:301) ~[Geyser-v1.16-b46.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [Geyser-v1.16-b46.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [Geyser-v1.16-b46.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [Geyser-v1.16-b46.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [Geyser-v1.16-b46.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [Geyser-v1.16-b46.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [Geyser-v1.16-b46.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [Geyser-v1.16-b46.jar:?]
        at io.netty.channel.epoll.EpollDatagramChannel.read(EpollDatagramChannel.java:688) [Geyser-v1.16-b46.jar:?]
        at io.netty.channel.epoll.EpollDatagramChannel.access$100(EpollDatagramChannel.java:57) [Geyser-v1.16-b46.jar:?]
        at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:507) [Geyser-v1.16-b46.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:502) [Geyser-v1.16-b46.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) [Geyser-v1.16-b46.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [Geyser-v1.16-b46.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-v1.16-b46.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

Possibly not necessarily related to the switch.

**Comment by bundabrg** [comment]
Caused by [this in Geyser](https://github.com/GeyserMC/Geyser/blob/41cb593dc43ae3058c552f2302d726f172ee6a9d/connector/src/main/java/org/geysermc/connector/skin/SkinManager.java#L270-L277)

Related to bedrock to bedrock skins and may be causing this issue due to https://github.com/GeyserMC/Geyser/pull/1184 as I run this on my server

**Comment by bundabrg** [comment]
Sorted by removing the improved logins for now in my bleeding build.
