### ISSUE TITLE
Education and Titles

### ISSUE THREAD

**Issue by bundabrg** [bundabrg/GeyserReversion#29]
```
com.nukkitx.protocol.bedrock.exception.PacketSerializeException: Error whilst serializing SetTitlePacket(type=TIMES, text=null, fadeInTime=0, stayTime=50, fadeOutTime=30)
        at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryEncode(BedrockPacketCodec.java:82) ~[Geyser-v1.16-b47.jar:?]
        at au.com.grieve.geyser.reversion.server.GeyserServerSession.sendPacket(GeyserServerSession.java:75) ~[?:?]
        at org.geysermc.connector.network.session.UpstreamSession.sendPacket(UpstreamSession.java:45) ~[Geyser-v1.16-b47.jar:?]
        at org.geysermc.connector.network.session.GeyserSession.lambda$sendUpstreamPacket$4(GeyserSession.java:827) ~[Geyser-v1.16-b47.jar:?]
        at org.geysermc.connector.event.EventResult.onNotCancelled(EventResult.java:59) ~[Geyser-v1.16-b47.jar:?]
        at org.geysermc.connector.network.session.GeyserSession.sendUpstreamPacket(GeyserSession.java:825) ~[Geyser-v1.16-b47.jar:?]
        at org.geysermc.connector.network.translators.java.JavaTitleTranslator.translate(JavaTitleTranslator.java:77) ~[Geyser-v1.16-b47.jar:?]
        at org.geysermc.connector.network.translators.java.JavaTitleTranslator.translate(JavaTitleTranslator.java:36) ~[Geyser-v1.16-b47.jar:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:100) [Geyser-v1.16-b47.jar:?]
        at org.geysermc.connector.network.session.GeyserSession.handleDownstreamPacket(GeyserSession.java:603) [Geyser-v1.16-b47.jar:?]
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:551) [Geyser-v1.16-b47.jar:?]
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) [Geyser-v1.16-b47.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) [Geyser-v1.16-b47.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) [Geyser-v1.16-b47.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException: string
        at com.nukkitx.network.util.Preconditions.checkNotNull(Preconditions.java:880) ~[Geyser-v1.16-b47.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockPacketHelper.writeString(BedrockPacketHelper.java:274) ~[Geyser-v1.16-b47.jar:?]
        at com.nukkitx.protocol.bedrock.v291.serializer.SetTitleSerializer_v291.serialize(SetTitleSerializer_v291.java:19) ~[Geyser-v1.16-b47.jar:?]
        at com.nukkitx.protocol.bedrock.v291.serializer.SetTitleSerializer_v291.serialize(SetTitleSerializer_v291.java:11) ~[Geyser-v1.16-b47.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockPacketSerializer.serialize(BedrockPacketSerializer.java:13) ~[Geyser-v1.16-b47.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryEncode(BedrockPacketCodec.java:80) ~[Geyser-v1.16-b47.jar:?]
        ... 14 more
> com.nukkitx.protocol.bedrock.exception.PacketSerializeException: Error whilst serializing SetTitlePacket(type=TIMES, text=null, fadeInTime=0, stayTime=50, fadeOutTime=30)
        at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryEncode(BedrockPacketCodec.java:82)
        at au.com.grieve.geyser.reversion.server.GeyserServerSession.sendPacket(GeyserServerSession.java:75)
        at org.geysermc.connector.network.session.UpstreamSession.sendPacket(UpstreamSession.java:45)
        at org.geysermc.connector.network.session.GeyserSession.lambda$sendUpstreamPacket$4(GeyserSession.java:827)
        at org.geysermc.connector.event.EventResult.onNotCancelled(EventResult.java:59)
        at org.geysermc.connector.network.session.GeyserSession.sendUpstreamPacket(GeyserSession.java:825)
        at org.geysermc.connector.network.translators.java.JavaTitleTranslator.translate(JavaTitleTranslator.java:77)
        at org.geysermc.connector.network.translators.java.JavaTitleTranslator.translate(JavaTitleTranslator.java:36)
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:100)
        at org.geysermc.connector.network.session.GeyserSession.handleDownstreamPacket(GeyserSession.java:603)
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:551)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: string
        at com.nukkitx.network.util.Preconditions.checkNotNull(Preconditions.java:880)
        at com.nukkitx.protocol.bedrock.BedrockPacketHelper.writeString(BedrockPacketHelper.java:274)
        at com.nukkitx.protocol.bedrock.v291.serializer.SetTitleSerializer_v291.serialize(SetTitleSerializer_v291.java:19)
        at com.nukkitx.protocol.bedrock.v291.serializer.SetTitleSerializer_v291.serialize(SetTitleSerializer_v291.java:11)
        at com.nukkitx.protocol.bedrock.BedrockPacketSerializer.serialize(BedrockPacketSerializer.java:13)
        at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryEncode(BedrockPacketCodec.java:80)
        ... 14 more

```

**Comment by bundabrg** [comment]
This may be because of my Bleeding fork. More testing needed.

**Comment by bundabrg** [comment]
Upstream issue.
