### ISSUE TITLE
Could not translate packet ServerPlayerListEntryPacket

### ISSUE THREAD

**Issue by bundabrg** [bundabrg/GeyserReversion#39]
```
java.lang.NullPointerException: null
	at org.geysermc.connector.GeyserConnector.getPlayerByUuid(GeyserConnector.java:374) ~[Geyser-v1.16-b54.jar:?]
	at org.geysermc.connector.skin.SkinManager.buildEntryManually(SkinManager.java:92) ~[Geyser-v1.16-b54.jar:?]
	at org.geysermc.connector.skin.SkinManager.buildCachedEntry(SkinManager.java:64) ~[Geyser-v1.16-b54.jar:?]
	at org.geysermc.connector.network.translators.java.entity.player.JavaPlayerListEntryTranslator.translate(JavaPlayerListEntryTranslator.java:89) ~[Geyser-v1.16-b54.jar:?]
	at org.geysermc.connector.network.translators.java.entity.player.JavaPlayerListEntryTranslator.translate(JavaPlayerListEntryTranslator.java:40) ~[Geyser-v1.16-b54.jar:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:100) [Geyser-v1.16-b54.jar:?]
	at org.geysermc.connector.network.session.GeyserSession.handleDownstreamPacket(GeyserSession.java:704) [Geyser-v1.16-b54.jar:?]
	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:669) [Geyser-v1.16-b54.jar:?]
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) [Geyser-v1.16-b54.jar:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) [Geyser-v1.16-b54.jar:?]
	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) [Geyser-v1.16-b54.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

# Affects
* Education

**Comment by bundabrg** [comment]
Upstream issue
