### ISSUE TITLE
Failed getting skin for {uuid}

### ISSUE THREAD

**Issue by bundabrg** [bundabrg/GeyserReversion#40]
```
2021-02-13 13:08:01.112 [ForkJoinPool.commonPool-worker-3] E - [31;1mFailed getting skin for {uuid}[0m
java.lang.NullPointerException: null
	at org.geysermc.connector.GeyserConnector.getPlayerByUuid(GeyserConnector.java:374) ~[Geyser-v1.16-b54.jar:?]
	at org.geysermc.connector.skin.SkinManager.buildEntryManually(SkinManager.java:92) ~[Geyser-v1.16-b54.jar:?]
	at org.geysermc.connector.skin.SkinManager.lambda$requestAndHandleSkinAndCape$0(SkinManager.java:174) ~[Geyser-v1.16-b54.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) [?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) [?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
```

**Comment by bundabrg** [comment]
Upstream Issue I'm pretty sure
