### ISSUE TITLE
Could not translate packet ServerEntityAnimationPacket

### ISSUE THREAD

**Issue by bundabrg** [bundabrg/GeyserReversion#41]
```
2021-02-13 13:12:09.035 [Thread-38] E - [31;1mCould not translate packet ServerEntityAnimationPacket[0m
com.nukkitx.protocol.bedrock.exception.PacketSerializeException: Error whilst serializing AnimatePacket(rowingTime=0.0, action=null, runtimeEntityId=11)
	at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryEncode(BedrockPacketCodec.java:82) ~[Geyser-v1.16-b54.jar:?]
	at au.com.grieve.geyser.reversion.server.GeyserServerSession.sendPacket(GeyserServerSession.java:75) ~[?:?]
	at org.geysermc.connector.network.session.UpstreamSession.sendPacket(UpstreamSession.java:45) ~[Geyser-v1.16-b54.jar:?]
	at org.geysermc.connector.network.session.GeyserSession.lambda$sendUpstreamPacket$6(GeyserSession.java:955) ~[Geyser-v1.16-b54.jar:?]
	at org.geysermc.connector.event.EventResult.onNotCancelled(EventResult.java:59) ~[Geyser-v1.16-b54.jar:?]
	at org.geysermc.connector.network.session.GeyserSession.sendUpstreamPacket(GeyserSession.java:953) ~[Geyser-v1.16-b54.jar:?]
	at org.geysermc.connector.network.translators.java.entity.JavaEntityAnimationTranslator.translate(JavaEntityAnimationTranslator.java:65) ~[Geyser-v1.16-b54.jar:?]
	at org.geysermc.connector.network.translators.java.entity.JavaEntityAnimationTranslator.translate(JavaEntityAnimationTranslator.java:36) ~[Geyser-v1.16-b54.jar:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:100) [Geyser-v1.16-b54.jar:?]
	at org.geysermc.connector.network.session.GeyserSession.handleDownstreamPacket(GeyserSession.java:704) [Geyser-v1.16-b54.jar:?]
	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:669) [Geyser-v1.16-b54.jar:?]
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) [Geyser-v1.16-b54.jar:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) [Geyser-v1.16-b54.jar:?]
	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) [Geyser-v1.16-b54.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at com.nukkitx.protocol.util.Int2ObjectBiMap.get(Int2ObjectBiMap.java:54) ~[Geyser-v1.16-b54.jar:?]
	at com.nukkitx.protocol.bedrock.v291.serializer.AnimateSerializer_v291.serialize(AnimateSerializer_v291.java:32) ~[Geyser-v1.16-b54.jar:?]
	at com.nukkitx.protocol.bedrock.v291.serializer.AnimateSerializer_v291.serialize(AnimateSerializer_v291.java:14) ~[Geyser-v1.16-b54.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockPacketSerializer.serialize(BedrockPacketSerializer.java:13) ~[Geyser-v1.16-b54.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryEncode(BedrockPacketCodec.java:80) ~[Geyser-v1.16-b54.jar:?]
	... 14 more
```

**Comment by bundabrg** [comment]
Upstream issue
