### ISSUE TITLE
Client is no longer informed if their school is not added

### ISSUE THREAD

**Issue by HandyHat** [bundabrg/GeyserReversion#5]
Before GeyserReversion became an extension, if the client's tenant wasn't added, they would be informed. Now, however, the client simply gets stuck at connecting to server - the console, however, still shows the correct error:

```
`18:22:28 ERROR] Failed to encrypt connection
au.com.grieve.reversion.exceptions.LoginException: Unknown Tenant tried to connect: a17ea00a-66f0-4a26-9458-68ad35e407f5
at au.com.grieve.reversion.editions.education.EducationLoginData.getHandshakeJwt(EducationLoginData.java:49) ~[?:?]
at au.com.grieve.geyser.reversion.editions.bedrock.handlers.BedrockUpstreamPacketHandler.handle(BedrockUpstreamPacketHandler.java:74) [?:?]
at com.nukkitx.protocol.bedrock.packet.LoginPacket.handle(LoginPacket.java:21) [Geyser-v1.16-b31.jar:?]
at au.com.grieve.reversion.editions.bedrock.BedrockReversionSession.toServer(BedrockReversionSession.java:91) [?:?]
at au.com.grieve.reversion.editions.bedrock.BedrockTranslator.toServer(BedrockTranslator.java:183) [?:?]
at au.com.grieve.reversion.editions.bedrock.BedrockTranslator.toDownstream(BedrockTranslator.java:169) [?:?]
at au.com.grieve.reversion.editions.bedrock.BedrockTranslator.fromUpstream(BedrockTranslator.java:98) [?:?]
at au.com.grieve.reversion.editions.bedrock.BedrockTranslator.fromClient(BedrockTranslator.java:141) [?:?]
at au.com.grieve.reversion.editions.bedrock.BedrockReversionSession$ReversionBatchHandler.handle(BedrockReversionSession.java:146) [?:?]
at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:275) [Geyser-v1.16-b31.jar:?]
at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32) [Geyser-v1.16-b31.jar:?]
at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) [Geyser-v1.16-b31.jar:?]
at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) [Geyser-v1.16-b31.jar:?]
at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) [Geyser-v1.16-b31.jar:?]
at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:400) [Geyser-v1.16-b31.jar:?]
at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) [Geyser-v1.16-b31.jar:?]
at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) [Geyser-v1.16-b31.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [Geyser-v1.16-b31.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [Geyser-v1.16-b31.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [Geyser-v1.16-b31.jar:?]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [Geyser-v1.16-b31.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [Geyser-v1.16-b31.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [Geyser-v1.16-b31.jar:?]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [Geyser-v1.16-b31.jar:?]
at io.netty.channel.epoll.EpollDatagramChannel.read(EpollDatagramChannel.java:688) [Geyser-v1.16-b31.jar:?]
at io.netty.channel.epoll.EpollDatagramChannel.access$100(EpollDatagramChannel.java:57) [Geyser-v1.16-b31.jar:?]
at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:507) [Geyser-v1.16-b31.jar:?]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:502) [Geyser-v1.16-b31.jar:?]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) [Geyser-v1.16-b31.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [Geyser-v1.16-b31.jar:?]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-v1.16-b31.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]`
```

Using Paper-141, Geyser-v1.16-b31 and GeyserReversion-1.0.10

**Comment by bundabrg** [comment]
Thanks. This should now show an error and disconnect the client.

**Comment by HandyHat** [comment]
Brilliant, thanks. The work you are doing for education support is great - it's something that we use daily and we really appreciate it. Keep up the good work!
